# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Pycharm_Project\QT\BaiDuDetect\objdetect.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
from detectimage import detect


class Ui_GroupBox(object):

    def __init__(self):
        self.imagePath = 'images/001.png'
        self.color = (0, 0, 255)
        self.file_path = 'c:/'

    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(1187, 901)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupBox.sizePolicy().hasHeightForWidth())
        GroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        GroupBox.setFont(font)
        GroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_img = QtWidgets.QLabel(GroupBox)
        self.label_img.setText("")
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.verticalLayout_5.addWidget(self.label_img)
        self.groupBox_2 = QtWidgets.QGroupBox(GroupBox)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.setVisible(False)
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.description = QtWidgets.QTextEdit(self.groupBox_2)
        self.description.setObjectName("description")
        font.setBold(False)
        self.description.setFont(font)
        self.gridLayout.addWidget(self.description, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.baikeurl = QtWidgets.QLineEdit(self.groupBox_2)
        self.baikeurl.setObjectName("baikeurl")
        font.setBold(False)
        self.baikeurl.setFont(font)
        self.gridLayout.addWidget(self.baikeurl, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.picurl = QtWidgets.QLineEdit(self.groupBox_2)
        self.picurl.setObjectName("picurl")
        font.setBold(False)
        self.picurl.setFont(font)
        self.gridLayout.addWidget(self.picurl, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_5.setStretch(0, 8)
        self.verticalLayout_5.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.upload = QtWidgets.QPushButton(GroupBox)
        self.upload.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setMinimumSize(QtCore.QSize(12, 0))
        self.upload.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.upload.setFont(font)
        self.upload.setAccessibleDescription("")
        self.upload.setShortcut("")
        self.upload.setAutoExclusive(True)
        self.upload.setDefault(False)
        self.upload.setFlat(False)
        self.upload.setObjectName("upload")
        self.verticalLayout.addWidget(self.upload, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(GroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.detect = QtWidgets.QPushButton(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detect.sizePolicy().hasHeightForWidth())
        self.detect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.detect.setFont(font)
        self.detect.setObjectName("detect")
        self.detect.setEnabled(False)
        self.verticalLayout.addWidget(self.detect, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(GroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.isbaike = QtWidgets.QCheckBox(GroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.isbaike.setFont(font)
        self.isbaike.setObjectName("isbaike")
        self.isbaike.setVisible(False)
        self.isbaike.toggled.connect(self.on_checkbox_toggled)
        self.verticalLayout.addWidget(self.isbaike, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.groupBox = QtWidgets.QGroupBox(GroupBox)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.cls = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cls.sizePolicy().hasHeightForWidth())
        self.cls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cls.setFont(font)
        self.cls.setAlignment(QtCore.Qt.AlignCenter)
        self.cls.setObjectName("cls")
        self.verticalLayout_3.addWidget(self.cls)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.score = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.score.sizePolicy().hasHeightForWidth())
        self.score.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.score.setFont(font)
        self.score.setLineWidth(2)
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setWordWrap(True)
        self.score.setIndent(0)
        self.score.setObjectName("score")
        self.verticalLayout_3.addWidget(self.score)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(3, 6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(GroupBox)
        self.upload.clicked.connect(self.on_upload_clicked)
        self.detect.clicked.connect(self.on_detect_clicked)
        self.pushButton.clicked.connect(self.on_choose_color)
        self.pushButton_2.clicked.connect(self.on_recognition_clicked)

        self.groupBox.setVisible(False)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "识别与检测"))
        GroupBox.setTitle(_translate("GroupBox", "通用物体识别与主题检测"))
        self.groupBox_2.setTitle(_translate("GroupBox", "百科信息"))
        self.label.setText(_translate("GroupBox", "百科描述"))
        self.label_2.setText(_translate("GroupBox", "百科链接"))
        self.label_3.setText(_translate("GroupBox", "百科图片"))
        self.upload.setText(_translate("GroupBox", "上传图像"))
        self.pushButton_2.setText(_translate("GroupBox", "图像识别"))
        self.detect.setText(_translate("GroupBox", "主题检测"))
        self.pushButton.setText(_translate("GroupBox", "边框颜色"))
        self.isbaike.setText(_translate("GroupBox", "百科信息"))
        self.groupBox.setTitle(_translate("GroupBox", "识别结果"))
        self.cls.setText(_translate("GroupBox", "笔记本电脑"))
        self.score.setText(_translate("GroupBox", "0.9876"))

    def on_upload_clicked(self):
        self.groupBox.setVisible(False)
        self.pushButton.setEnabled(False)
        fname = QtWidgets.QFileDialog.getOpenFileName(QtWidgets.QWidget(), 'Open file', self.file_path,
                                                      'Image file (*.jpg *.gif *.png)')
        if fname[0] != '':
            self.file_path = os.path.dirname(fname[0])
            self.imagePath = fname[0]
        pixmap = QtGui.QPixmap(self.imagePath)
        height, width = pixmap.height(), pixmap.width()
        if width > height:
            pixmapscared = pixmap.scaledToWidth(800)
        else:
            pixmapscared = pixmap.scaledToHeight(600)
        self.label_img.setPixmap(pixmapscared)
        # self.label_img.setScaledContents(True)
        self.detect.setEnabled(True)
        self.pushButton_2.setEnabled(True)

    def on_recognition_clicked(self):
        self.isbaike.setVisible(True)
        str_warm = '未查到相关信息'
        img, name, score, baike = detect(self.imagePath, self.color)
        pixmap = QtGui.QPixmap(self.imagePath)
        height, width = pixmap.height(), pixmap.width()
        if width > height:
            pixmapscared = pixmap.scaledToWidth(800)
        else:
            pixmapscared = pixmap.scaledToHeight(600)
        self.label_img.setPixmap(pixmapscared)
        self.groupBox.setVisible(True)
        # self.label_img.setScaledContents(True)
        self.cls.setText(name)
        self.score.setText(str(score))
        self.detect.setEnabled(True)
        if baike:
            self.description.setText(baike['description'])
            self.baikeurl.setText(baike['baike_url'])
            self.picurl.setText(baike['image_url'])
        else:
            self.description.setText(str_warm)
            self.baikeurl.setText(str_warm)
            self.picurl.setText(str_warm)

    def on_choose_color(self):
        self.groupBox.setVisible(False)
        color = QtWidgets.QColorDialog.getColor()
        self.color = color.getRgb()[:3]
        from detectimage import detect
        img, name, score, _ = detect(self.imagePath, self.color)
        height, width, bytesPerComponent = img.shape
        bytesPerLine = bytesPerComponent * width
        Qimg = QtGui.QImage(img.data, width, height, bytesPerLine, QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(Qimg)
        if width > height:
            pixmapscared = pixmap.scaledToWidth(800)
        else:
            pixmapscared = pixmap.scaledToHeight(600)
        self.label_img.setPixmap(pixmapscared)
        # self.label_img.setScaledContents(True)
        self.cls.setText(" ")
        self.score.setText(" ")

    def on_detect_clicked(self):
        self.groupBox.setVisible(False)
        self.groupBox_2.setVisible(False)
        self.pushButton_2.setEnabled(False)
        self.isbaike.setVisible(False)
        self.cls.setText(" ")
        self.score.setText(" ")
        img, name, score, _ = detect(self.imagePath, self.color)
        height, width, bytesPerComponent = img.shape
        bytesPerLine = bytesPerComponent * width
        Qimg = QtGui.QImage(img.data, width, height, bytesPerLine, QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(Qimg)
        if width > height:
            pixmapscared = pixmap.scaledToWidth(800)
        else:
            pixmapscared = pixmap.scaledToHeight(600)
        self.label_img.setPixmap(pixmapscared)
        # self.label_img.setScaledContents(True)
        self.detect.setEnabled(False)
        self.pushButton.setEnabled(True)

    def on_checkbox_toggled(self):
        if self.isbaike.isChecked():
            self.groupBox_2.setVisible(True)
        else:
            self.groupBox_2.setVisible(False)

